import org.junit.Test;

import com.spachava.binarytree.Library;

import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'spmega' at '3/11/17 2:27 PM' with Gradle 2.14
 *
 * @author spmega, @date 3/11/17 2:27 PM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
