package com.spachava.binarytree;
/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'spmega' at '3/11/17 2:27 PM' with Gradle 2.14
 *
 * @author spmega, @date 3/11/17 2:27 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
